name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4.1.7

      - name: Instalar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.1'
          